### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by T3TzzZ** [tommenx/wxss#6]
可以留个联系方式吗？ 想请教你一些问题>,<

**Comment by T3TzzZ** [comment]
hi^^

**Comment by T3TzzZ** [comment]
为啥关了呀

**Comment by tommenx** [comment]
issue是用来描述你有什么问题的呀，如果没有什么问题，就关了
________________________________
发件人: T3TzzZ <notifications@github.com>
发送时间: 2019年5月25日 1:03
收件人: tommenx/wxss
抄送: zeng xiang; State change
主题: Re: [tommenx/wxss] 你好 (#6)


为啥关了呀

―

**Comment by T3TzzZ** [comment]
我好菜呀hahah

**Comment by T3TzzZ** [comment]
还以为你不会看到我的留言了
